config/routes.rb
LighthouseCommercial::Application.routes.draw do
  
  resources :contact_messages, only: ["index","create"]

  resources :recent_transactions

  resources :testimonials

  match "home" => "static_pages#home"
  match "about_us" => "static_pages#about_us"
  match "advantage" => "static_pages#advantage"
  match "recent_assignments" => "static_pages#recent_transactions"
  match "loan_programs" => "static_pages#loan_programs"
  match "contact_us" => "static_pages#contact_us"
  match "customer_testimonials" => "static_pages#testimonials"
  match "legal_info" => "static_pages#legal_information"
  
  

  root :to => 'static_pages#home'

end

app/models/contact_message.rb
class ContactMessage < ActiveRecord::Base
  attr_accessible :content, :email
  
  
end

app/models/recent_transaction.rb
class RecentTransaction < ActiveRecord::Base
  attr_accessible :amount, :image, :location, :name, :property_type
  
  mount_uploader :image, ImageUploader
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :content, :source
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  # GET /contact_messages
  # GET /contact_messages.json
  def index
    @contact_messages = ContactMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contact_messages }
    end
  end


  # GET /contact_messages/1/edit
  def edit
    @contact_message = ContactMessage.find(params[:id])
  end

  # POST /contact_messages
  # POST /contact_messages.json
  def create
    @contact_message = ContactMessage.new(params[:contact_message])
    if @contact_message.save
      ContactFormMailer.new_contact_us_message(@contact_message.email, @contact_message.content).deliver
      flash[:success] = "Thank you for contacting us. We will respond as soon as we possibly can"
      redirect_to root_url
    else
      flash[:error] = "We were unable to complete the contact form. Please email us at manderson@lighthouse-commercial.com"
      redirect_to contact_us_path
    end
  end


end

app/controllers/recent_transactions_controller.rb
class RecentTransactionsController < ApplicationController
  # GET /recent_transactions
  # GET /recent_transactions.json
  def index
    @recent_transactions = RecentTransaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recent_transactions }
    end
  end

  # GET /recent_transactions/1
  # GET /recent_transactions/1.json
  def show
    @recent_transaction = RecentTransaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recent_transaction }
    end
  end

  # GET /recent_transactions/new
  # GET /recent_transactions/new.json
  def new
    @recent_transaction = RecentTransaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recent_transaction }
    end
  end

  # GET /recent_transactions/1/edit
  def edit
    @recent_transaction = RecentTransaction.find(params[:id])
  end

  # POST /recent_transactions
  # POST /recent_transactions.json
  def create
    @recent_transaction = RecentTransaction.new(params[:recent_transaction])

    respond_to do |format|
      if @recent_transaction.save
        format.html { redirect_to @recent_transaction, notice: 'Recent transaction was successfully created.' }
        format.json { render json: @recent_transaction, status: :created, location: @recent_transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @recent_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recent_transactions/1
  # PUT /recent_transactions/1.json
  def update
    @recent_transaction = RecentTransaction.find(params[:id])

    respond_to do |format|
      if @recent_transaction.update_attributes(params[:recent_transaction])
        format.html { redirect_to @recent_transaction, notice: 'Recent transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recent_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recent_transactions/1
  # DELETE /recent_transactions/1.json
  def destroy
    @recent_transaction = RecentTransaction.find(params[:id])
    @recent_transaction.destroy

    respond_to do |format|
      format.html { redirect_to recent_transactions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about_us
  end
  
  def advantage
  end
  
  def recent_transactions
    @recent_transactions = RecentTransaction.all
  end
  
  def loan_programs
    
  end
  
  def contact_us
    @contact_message = ContactMessage.new    
  end
  
  def testimonials
    @testimonials = Testimonial.all
  end
  
  def legal_information
    
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonials }
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.json
  def new
    @testimonial = Testimonial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/1/edit
  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(params[:testimonial])

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render json: @testimonial, status: :created, location: @testimonial }
      else
        format.html { render action: "new" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testimonials/1
  # PUT /testimonials/1.json
  def update
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      if @testimonial.update_attributes(params[:testimonial])
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    respond_to do |format|
      format.html { redirect_to testimonials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/helpers/recent_transactions_helper.rb
module RecentTransactionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/contact_messages/_form.html.erb
<%= form_for(@contact_message) do |f| %>
  <% if @contact_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_message.errors.count, "error") %> prohibited this contact_message from being saved:</h2>

      <ul>
      <% @contact_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_messages/edit.html.erb
<h1>Editing contact_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_message %> |
<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/index.html.erb
<h1>Listing contact_messages</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contact_messages.each do |contact_message| %>
  <tr>
    <td><%= contact_message.email %></td>
    <td><%= contact_message.content %></td>

  </tr>
<% end %>
</table>

<br />

app/views/contact_messages/new.html.erb
<h1>New contact_message</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @contact_message.email %>
</p>

<p>
  <b>Content:</b>
  <%= @contact_message.content %>
</p>


<%= link_to 'Edit', edit_contact_message_path(@contact_message) %> |
<%= link_to 'Back', contact_messages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<%= favicon_link_tag 'favicon_lcm.png' %>
  	<title><%= content_for?(:title) ? yield(:title) : "Access to Capital || Lighthouse Commercial Mortgage" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
		<div class="row">
		  <div class="large-3 columns">
				<%= link_to (image_tag "lcm_logo.jpg"), root_url %>
		  </div>
		  <div class="large-9 columns">
		    <ul class="inline-list right">
		      <li><%= link_to "About Us", about_us_path, class: 'small button round' %></li>
		      <li><%= link_to "Recent Assignments", recent_assignments_path, class: 'small button round' %></li>
					<li><%= link_to "Loan Programs", loan_programs_path, class: 'small button round' %></li>
		      <li><%= link_to "Contact Us", contact_us_path, class: 'small button round' %></li>
		      <li><%= link_to "Testimonials", customer_testimonials_path, class: 'small button round' %></li>
		    </ul>
		  </div>
		</div>

		<div class="row">
   		<%= yield %>
		</div>
		<!-- Footer -->

		<% if controller.action_name == "home" %>
			<%= render "shared/legal_footer" %>
		<% else %>
			<%= render "shared/home_footer" %>
		<% end %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/loan_programs/_bridge.html.erb
<div class="large-12 large-centered columns">
	<div class="row">
		<div class="large-8 columns">
			<h3>Bridge Financing <br><span class="subheader">Indicative Terms:</span></h3>

		</div>
		<div class="large-4 columns">

		</div>
	</div>

	<!-- <div class="row">
		<ul data-orbit>
		  <li data-orbit-slide="headline-1">
		    <p>Pellentesque habitant morbi tristique senectus.</p>
		  </li>
		  <li data-orbit-slide="headline-2">
		    <p>Pellentesque habitant morbi tristique senectus.</p>
		  </li>
		  <li data-orbit-slide="headline-3">
		    <p>Pellentesque habitant morbi tristique senectus.</p>
		  </li>
		</ul>
	</div> -->
	<div class="row">
		<div class="large-12 columns">
			<ul class="inline-list">
				<li><div class="property_type"><h5 style=" padding:7px;">Apartments</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Hotel</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Industrial</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Mixed Use</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Office</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Retail</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Self-Storage</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Single Tenant</h5></div></li>
			</ul>
		</div>
	</div>
	<table>
	  <tbody>
	    <tr>
	      <td class="lead">Loan Amount</td>
	      <td class="lead spec">$25,000,000 and up</td>
	    </tr>
			<tr>
	      <td class="lead">Loan-to-Value</td>
	      <td class="lead spec">75% Maximum</td>
	    </tr>
			<tr>
	      <td class="lead">Loan Term</td>
	      <td class="lead spec">2 to 3 Years</td>
	    </tr>
			<tr>
	      <td class="lead">Amortization</td>
	      <td class="lead spec">Interest Only</td>
	    </tr>
			<tr>
	      <td class="lead">Origination Fee</td>
	      <td class="lead spec">Customary 1%</td>
	    </tr>
			<tr>
	      <td class="lead">Lender Fee</td>
	      <td class="lead spec">Typically 1 to 2%</td>
	    </tr>	
			<tr>
	      <td class="lead">Pricing</td>
	      <td class="lead spec">250 to 400 bps over LIBOR</td>
	    </tr>
			<tr>
	      <td class="lead">Borrowing Entity</td>
	      <td class="lead spec">A bankruptcy-remote Special Purpose Entity</td>
	    </tr>
			<tr>
	      <td class="lead">Recourse</td>
	      <td class="lead spec">Full Recourse (Non-Recourse in select cases)</td>
	    </tr>

	  </tbody>
	</table>
</div>

app/views/loan_programs/_cmbs.html.erb
<div class="large-12 large-centered columns">
	<div class="row">
		<div class="large-8 columns">
			<h3>CMBS Loans <br><span class="subheader">Indicative Terms:</span></h3>

		</div>
		<div class="large-4 columns">
			<p><%= link_to "Download a PDF Copy", "https://s3.amazonaws.com/lighthouse_commercial_production/loan_programs/cmbs_program.pdf", target: "_blank" %></p>
		</div>
	</div>

	<!-- <div class="row">
		<ul data-orbit>
		  <li data-orbit-slide="headline-1">
		    <p>Pellentesque habitant morbi tristique senectus.</p>
		  </li>
		  <li data-orbit-slide="headline-2">
		    <p>Pellentesque habitant morbi tristique senectus.</p>
		  </li>
		  <li data-orbit-slide="headline-3">
		    <p>Pellentesque habitant morbi tristique senectus.</p>
		  </li>
		</ul>
	</div> -->
	<div class="row">
		<div class="large-12 columns">
			<ul class="inline-list">
				<li><div class="property_type"><h5 style=" padding:7px;">Apartments</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Hotel</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Industrial</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Mixed Use</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Mobile Home Parks</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Office</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Retail</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Self-Storage</h5></div></li>
				<li><div class="property_type"><h5 style=" padding:7px;">Single Tenant</h5></div></li>
			</ul>
		</div>
	</div>
	<table>
	  <tbody>
	    <tr>
	      <td class="lead">Loan Amount</td>
	      <td class="lead spec">$2,500,000 and up</td>
	    </tr>
			<tr>
	      <td class="lead">Loan-to-Value</td>
	      <td class="lead spec">75% Maximum</td>
	    </tr>
			<tr>
	      <td class="lead">Debt Yield</td>
	      <td class="lead spec">8.25% Minimum (10% for Hotels)</td>
	    </tr>
			<tr>
	      <td class="lead">Loan Term</td>
	      <td class="lead spec">5 and 10 Years</td>
	    </tr>
			<tr>
	      <td class="lead">Amortization</td>
	      <td class="lead spec">20-30 Years (I/O available on a select basis)</td>
	    </tr>
			<tr>
	      <td class="lead">Origination Fee</td>
	      <td class="lead spec">Customary 1%</td>
	    </tr>
			<tr>
	      <td class="lead">Borrowing Entity</td>
	      <td class="lead spec">A bankruptcy-remote Special Purpose Entity</td>
	    </tr>
			<tr>
	      <td class="lead">Recourse</td>
	      <td class="lead spec">Non-recourse, excluding the usual 'bad boy' carve outs</td>
	    </tr>
			<tr>
	      <td class="lead">Reserves</td>
	      <td class="lead spec">Required for Replacements, Tenant Improvements & Leasing Commissions</td>
	    </tr>
			<tr>
	      <td class="lead">Prepayment</td>
	      <td class="lead spec">Loans may be defeased after a lockout period</td>
	    </tr>
			<tr>
	      <td class="lead">Assumability</td>
	      <td class="lead spec">1% for qualifying borrowers</td>
	    </tr>
			<tr>
	      <td class="lead">Ownership Transfers</td>
	      <td class="lead spec">Very limited, except for estate planning purposes</td>
	    </tr>
			<tr>
	      <td class="lead">Cash Mgmt.</td>
	      <td class="lead spec">Lock box is usually required and will be Springing or Hard</td>
	    </tr>
	  </tbody>
	</table>
</div>

app/views/loan_programs/_construction.html.erb
<div class="large-12 large-centered columns">
	<div class="row">
		<div class="large-8 columns">
			<h3>Construction Financing Program <br><span class="subheader">Indicative Terms:</span></h3>
			<p class="subheader">
				Construction financing is available from a variety of life insurance companies and commercial banks.
				Below are the general parameters that we consider representative of the lenders we represent.
			</p>
		</div>
		<div class="large-4 columns">
			<p><%= link_to "Download a PDF Copy", "https://s3.amazonaws.com/lighthouse_commercial_production/loan_programs/construction_program.pdf", target: "_blank" %></p>
		</div>
	</div>
	<table>
	  <tbody>
	    <tr>
	      <td class="lead">Loan Amount</td>
	      <td class="lead spec">$3,000,000 and up for commercial banks</td>
	    </tr>
			<tr>
				<td class="lead"> </td>
				<td class="lead spec">$15,000,000 and up for life companies</td>
			</tr>
			<tr>
	      <td class="lead">Loan-to-Value</td>
	      <td class="lead spec">Up to 75% of the "As Completed" appraised value</td>
	    </tr>
			<tr>
	      <td class="lead">Loan-to-Cost</td>
	      <td class="lead spec">75 to 85% (up to 90% with equity participation from lender)</td>
	    </tr>
			<tr>
	      <td class="lead">Loan Term</td>
	      <td class="lead spec">20 to 60 months for construction only loan and up to 30 years for construction/perm loans</td>
	    </tr>
			<tr>
	      <td class="lead">Origination Fee</td>
	      <td class="lead spec">Customary 1%</td>
	    </tr>
			<tr>
	      <td class="lead">Borrowing Entity</td>
	      <td class="lead spec">A bankruptcy-remote Special Purpose Entity may be required</td>
	    </tr>
			<tr>
	      <td class="lead">Recourse</td>
	      <td class="lead spec">Typically, full recourse is required,  except for loans in excess of $25MM or equity participation loans, excluding the standard 'bad boy' carve-outs</td>
	    </tr>
	  </tbody>
	</table>
	<hr>
	<div class="row">
		<div class="large-3 columns">
			<h5 class="subheader">Market Analysis</h5>
			<p>
				Required for all multifamily and hospitality loans and may be required for other property types
			</p>
		</div>
		<div class="large-3 columns">
			<h5 class="subheader">Preleasing</h5>
			<p>
				Required for single tenant properties, percentage requirement for multi-tenant properties, but not required for multifamily
			</p>
		</div>
		<div class="large-3 columns">
			<h5 class="subheader">Separate Parcel</h5>
			<p>
				Typically, the collateral for the transaction must have a separate tax parcel to qualify
			</p>
		</div>
		<div class="large-3 columns">
			<h5 class="subheader">Assignment</h5>
			<p>
				Requires lender approval in all cases
			</p>
		</div>
	</div>
</div>

app/views/recent_transactions/_form.html.erb
<%= form_for @recent_transaction, :html => { :multipart => true } do |f| %>
  <% if @recent_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recent_transaction.errors.count, "error") %> prohibited this recent_transaction from being saved:</h2>

      <ul>
      <% @recent_transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br />
    <%= f.text_field :property_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recent_transactions/edit.html.erb
<h1>Editing recent_transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @recent_transaction %> |
<%= link_to 'Back', recent_transactions_path %>

app/views/recent_transactions/index.html.erb
<div class="large-8 columns">
<h1>Listing recent_transactions</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Amount</th>
    <th>Location</th>
    <th>Property type</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recent_transactions.each do |recent_transaction| %>
  <tr>
    <td><%= truncate recent_transaction.image_url.to_s, length: 50 %></td>
    <td><%= recent_transaction.amount %></td>
    <td><%= recent_transaction.location %></td>
    <td><%= recent_transaction.property_type %></td>
    <td><%= recent_transaction.name %></td>
    <td><%= link_to 'Show', recent_transaction %></td>
    <td><%= link_to 'Edit', edit_recent_transaction_path(recent_transaction) %></td>
    <td><%= link_to 'Destroy', recent_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recent transaction', new_recent_transaction_path %>
</div>

app/views/recent_transactions/new.html.erb
<h1>New recent_transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', recent_transactions_path %>

app/views/recent_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @recent_transaction.image %>
</p>

<p>
  <b>Amount:</b>
  <%= @recent_transaction.amount %>
</p>

<p>
  <b>Location:</b>
  <%= @recent_transaction.location %>
</p>

<p>
  <b>Property type:</b>
  <%= @recent_transaction.property_type %>
</p>

<p>
  <b>Name:</b>
  <%= @recent_transaction.name %>
</p>


<%= link_to 'Edit', edit_recent_transaction_path(@recent_transaction) %> |
<%= link_to 'Back', recent_transactions_path %>

app/views/shared/_home_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-6 columns">

      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><%= link_to "Home", root_url %></li>
          
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_legal_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-5 columns">

      </div>
      <div class="large-7 columns">
        <ul class="inline-list right">
					<li><%= image_tag("icsc_logo.gif") %></li>
					<li><%= image_tag("MBA_Member_logo.jpg", width: '90px' ) %></li>
          <li><%= link_to "Legal Information", legal_info_path %></li>
          
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/static_pages/recent_transactions.html.erb
<div class="large-8 large-centered columns">
	<h2 class="subheader">A Sample of Our Recent Work</h2>
	<% @recent_transactions.each do |transaction| %>
		<div class="row">

			<div class="large-4 columns">
				<% unless transaction.image.blank? %>
					<% if File.extname(transaction.image_url.to_s) == '.pdf' %>
						<%= link_to image_tag("http://placehold.it/250x250&text=View PDF"), transaction.image_url.to_s %>
					<% else %>
						<%= image_tag transaction.image_url.to_s, width: '200px', height: '250px' %>
					<% end %>
				<% else %>
					<%= image_tag "http://placehold.it/250x250&text=No Image Available" %>
				<% end %>	
			</div>

			<div class="large-6 large-offset-2 columns">
				<h5><span class="subheader">Property Type:</span> <%= transaction.property_type %></h5>
				<p><span class="subheader">Loan Amount:</span> <%= transaction.amount %></br>
				<span class="subheader">Location: </span><%= transaction.location %></p>
			</div>
			<div class="emptySpace"></div>
		</div>
	<% end %>
</div>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<div class="large-8 large-centered columns">
	
		<h1>Listing testimonials</h1>

		<table>
		  <tr>
		    <th>Content</th>
		    <th>Source</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>

		<% @testimonials.each do |testimonial| %>
		  <tr>
		    <td><%= testimonial.content %></td>
		    <td><%= testimonial.source %></td>
		    <td><%= link_to 'Show', testimonial %></td>
		    <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
		    <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
		</table>

		<br />

		<%= link_to 'New Testimonial', new_testimonial_path %>

</div>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @testimonial.content %>
</p>

<p>
  <b>Source:</b>
  <%= @testimonial.source %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>